import { FormEvent } from 'react'
import { Button, Input, Label, TextArea } from '@heroui/react'
import type { WorkContent } from '../api'

export type ContentDraft = { title: string; detailed_record: string; technical_materials: string; result_data: string; supplementary_notes: string }
type Props = { contents: WorkContent[]; draft: ContentDraft; editingId: number | null; onDraftChange: (draft: ContentDraft) => void; onStartEdit: (item: WorkContent) => void; onSubmit: (event: FormEvent) => void; onCancel: () => void; onMove: (index: number, direction: -1 | 1) => void; onArchive: (item: WorkContent) => void }

export function WorkContentEditor({ contents, draft, editingId, onDraftChange, onStartEdit, onSubmit, onCancel, onMove, onArchive }: Props) {
  return <>
    <div className="content-list-header"><h3>具体工作内容</h3><span>{contents.length} 条</span></div>
    <div className="content-list">{contents.map((item, index) => <article key={item.id} className={`content-card ${item.archived ? 'archived' : ''}`}><div className="content-card-heading"><button className="content-title" onClick={() => onStartEdit(item)}>{item.title}</button><div className="content-actions"><Button size="sm" variant="ghost" onPress={() => onMove(index, -1)} isDisabled={index === 0}>上移</Button><Button size="sm" variant="ghost" onPress={() => onMove(index, 1)} isDisabled={index === contents.length - 1}>下移</Button><Button size="sm" variant="secondary" onPress={() => onArchive(item)}>{item.archived ? '恢复' : '归档'}</Button></div></div><p>{item.detailed_record || '暂无详细记录'}</p><dl><div><dt>技术材料</dt><dd>{item.technical_materials || '—'}</dd></div><div><dt>结果数据</dt><dd>{item.result_data || '—'}</dd></div><div><dt>补充说明</dt><dd>{item.supplementary_notes || '—'}</dd></div></dl></article>)}{!contents.length && <div className="empty-copy">还没有具体工作内容。可以先添加一条工作贡献，再补充详细记录、技术材料和结果数据。</div>}</div>
    <form className="stack-form content-form" onSubmit={onSubmit}><h3>{editingId ? '编辑具体工作内容' : '新增具体工作内容'}</h3><div className="field"><Label htmlFor="content-title">标题</Label><Input id="content-title" value={draft.title} onChange={event => onDraftChange({ ...draft, title: event.target.value })} required /></div><div className="field"><Label htmlFor="content-record">详细记录</Label><TextArea id="content-record" value={draft.detailed_record} onChange={event => onDraftChange({ ...draft, detailed_record: event.target.value })} /></div><div className="field"><Label htmlFor="content-materials">技术材料</Label><TextArea id="content-materials" value={draft.technical_materials} onChange={event => onDraftChange({ ...draft, technical_materials: event.target.value })} /></div><div className="field"><Label htmlFor="content-result">结果数据</Label><TextArea id="content-result" value={draft.result_data} onChange={event => onDraftChange({ ...draft, result_data: event.target.value })} /></div><div className="field"><Label htmlFor="content-notes">补充说明</Label><TextArea id="content-notes" value={draft.supplementary_notes} onChange={event => onDraftChange({ ...draft, supplementary_notes: event.target.value })} /></div><div className="form-actions"><Button type="submit" variant="primary">{editingId ? '保存具体工作内容' : '添加具体工作内容'}</Button>{editingId && <Button type="button" variant="ghost" onPress={onCancel}>取消编辑</Button>}</div></form>
  </>
}
